dist: trusty
language: node_js
node_js:
  - "10"
  - "11"
  - "12"
  - "13"
  - "14"
install:
  - npm install
script: npm run lint && npm run build && npm test
before_deploy: npm run build
deploy:
  provider: npm
  email: development@platforme.com
  skip_cleanup: true
  api_key:
    secure: AIZ8cO62zBmQOcBXv5Z89Pcqkr3kGGDtmFn7iYMhYfUxj45sGZMCFgQyuDAYxBnFXFmlKgxrpsgI83kDoO0Zfn58cSah1kwYi0DuMy8CxrZIEKSV/6XcuPtuOuDq9rDF51hFB3cpCCU4xEYG/n/9s/ucHiypCU1LhcxFq3N5Se99TIrzoBCpMObh5ludsSWO/Q8dvEkBJmntfLu1CPF7DNRD5NrhphMWr2QpxW9LeZIglNdU3g8qmbLQv1Dy5Iv0HIG+y8YMFzf6O336jfAXp5HkfgeZPxvumfLGxjUAGa9BMUK5URb196Se0C4MxvLqDHGFYzOe3heUvOrTTCZa3Xg+1CNgDIkai+1eWgOl+Xh4LRE9iWhfVtze3VAkyf6hEEZ6UMPKWv36lvgSVNKkg4Z0WYH6KTujAoDDJWYoiI3aa6wArdpzyPouCiN7i4fiJYNIlQtEUL7HrL+h14kOWzQMG7WDuYjCx+bcnHLSMOLXSbvDbO+LAo85ldiYwTTfy9lB/SP1uyyvb1gO3QH5GurSRACCYoOSYm9/F0HbNKvNiKjGt/HiiwBuDQqTQBbPcreCmG1ilX9hqtCjb2PGgjG6y/nhwfHao6r1PuOVFOsJtNpOlm4dO5gK39eULgGBGtIfl3PKkZ2+LYNKC6AFsitgLSdPkcReu3yfTxES0rk=
  on:
    tags: true
    node_js: "10"
